ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER user_pty IDENTIFIED BY "duoc"
--DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER user_pty QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO user_pty;
GRANT "RESOURCE" TO user_pty;
ALTER USER user_pty DEFAULT ROLE "RESOURCE";