CREATE SEQUENCE seq_comuna;
CREATE SEQUENCE seq_empresa;
-- Tabla Comuna
INSERT INTO comuna VALUES(seq_comuna.NEXTVAL, 'CONCEPCION');
INSERT INTO comuna VALUES(seq_comuna.NEXTVAL, 'SAN PEDRO DE LA PAZ');
INSERT INTO comuna VALUES(seq_comuna.NEXTVAL, 'TALCAHUANO');
-- Tabla Empresa
INSERT INTO empresa VALUES(seq_empresa.NEXTVAL, 'EMPRESA A');
INSERT INTO empresa VALUES(seq_empresa.NEXTVAL, 'EMPRESA B');
INSERT INTO empresa VALUES(seq_empresa.NEXTVAL, 'EMPRESA C');
-- Tabla Colaborador
INSERT INTO colaborador VALUES(15015410,'DOLORES BARRIGA', 1, 1);
INSERT INTO colaborador VALUES(21346561,'AQUILES CASTRO', 2, 1);
INSERT INTO colaborador VALUES(16361195,'ALEJANDRA GUZMAN', 2, 2);
INSERT INTO colaborador VALUES(13265937,'HELENA HUERTA', 3, 2);
INSERT INTO colaborador VALUES(9818870,'SANDRO JIMENEZ', 2, 2);
